
# Code to load and format data (generated by shell and highlow.shell) and generate plots for publication.
# Plots are generated in pdf format and saved in the adjacent manuscript folder to be incorporated into 
# the latex file.

# Note that loading the patch data can take up to a few minutes.


#Choose the landscape structure to generate plots for:
#   full = fully connected - all patches equally accessible from all other patches
#   lattice = lattice structure - each patch has four accessible neighbors

conn <- "(full)"
conn <- "(lattice)"
conn <- "(x0)"
conn <- "(delta)"


# Metapopulation-level results
#===============================================================

load(paste(getwd(), "/Data/out", conn, ".Rdata", sep = ""))

library(gridExtra)
library(lattice)
library(RColorBrewer)

metapop.S <- tapply(out$Sfin, list(out$longevity, out$variance), mean)
metapop.I <- tapply(out$Ifin, list(out$longevity, out$variance), mean)

metapop.pan <- tapply(out$Sfin == 0 & out$Ifin > 0, list(out$longevity, out$variance), sum) / 100
metapop.end <- tapply(out$Sfin > 0 & out$Ifin > 0, list(out$longevity, out$variance), sum) / 100
metapop.ext <- tapply(out$Sfin == 0 & out$Ifin == 0, list(out$longevity, out$variance), sum) / 100
metapop.nd <- tapply(out$Sfin > 0 & out$Ifin == 0, list(out$longevity, out$variance), sum) / 100

p.pan <- levelplot(metapop.pan, col.regions = brewer.pal(9, "Reds"), xlab = "Longevity", ylab = "Variance", 
                   at = seq(0, 100, by = 12.5), colorkey = F, scales = list(at = c(1, 3, 5, 7, 9)))
p.end <- levelplot(metapop.end, col.regions = brewer.pal(9, "Reds"), cuts = 8, xlab = "Longevity", ylab = "Variance", 
                   at = seq(0, 100, by = 12.5), colorkey = F, scales = list(at = c(1, 3, 5, 7, 9))
p.ext <- levelplot(metapop.ext, col.regions = brewer.pal(9, "Reds"), cuts = 8, xlab = "Longevity", ylab = "Variance",
                   scales = list(at = c(1, 3, 5, 7, 9))
p.nd <- levelplot(metapop.nd, col.regions = brewer.pal(9, "Reds"), cuts = 8, xlab = "Longevity", ylab = "Variance",
                  scales = list(at = c(1, 3, 5, 7, 9))

key <- draw.colorkey(list(col = brewer.pal(9, "Reds"), 
                          at = seq(0, 100, by = 12.5),
                          labels = list(at = seq(0, 100, by = 25)),
                          height = 0.7), 
                     draw = F)

pdf(paste(getwd(), "/Manuscript", "/metapop", conn, ".pdf", sep=""), height=5, width=10)

grid.arrange(p.end, p.pan, key, ncol = 3, widths = c(0.45, 0.45, 0.1))

dev.off()

#===============================================================================

# Plotting logistic regression surface for prob. of pathogen persistence
# (no longer in use -- needless level of abstraction from actual results)

# # Generating pathogen persistence and pandemic indicator vectors
# persists <- (metapop$I>0)
# pandemic <- (metapop$I>0 & metapop$S==0)
# 
# logistic.per <- glm(formula = persists ~ metapop$var*metapop$longevity, family = binomial(link = "logit"))
# logistic.pan <- glm(formula = pandemic[persists] ~ metapop$var[persists]*metapop$longevity[persists], 
#                     family = binomial(link = "logit"))
# 
# p.per <- predict(logistic.per, type="response")
# p.pan <- predict(logistic.pan, type="response")
# 
# plot.data <- data.frame(c(p.per, p.pan), rbind(metapop[c("var", "longevity")], metapop[persists, c("var", "longevity")]),
#                         rep(c(1,2), times = c(length(persists), sum(persists))))
# names(plot.data) <- c("p", "var", "longevity", "perpan")
# 
# trellis.par.set("axis.line", list(col="transparent"), las=0)
# wireframe(p ~ var + longevity | perpan, data=plot.data,
#           scales = list(arrows=FALSE, cex=1.2, col="black", tck=1.4, z = list(distance=1.2)),
#           xlab = list(label="variance", cex=1.2, font=2, rot=30),
#           ylab = list(label="longevity", cex=1.2, font=2, rot=320),
#           zlab = list(label="Probability of outcome", cex=1.2, font=2, rot=93),
#           layout = c(2, 1), strip=F,
#           shade=F, col="gray50")
# 
# dev.off()


# High/low sensitivity analysis results
#===============================================================

highlow<-read.csv(paste(getwd(), "/Data/highlow", conn, ".csv", sep = ""), header=TRUE)

highlow<-highlow[,-1]

pdf(paste(getwd(), "/Manuscript", "/highlow", conn, ".pdf", sep=""), height=5, width=10)

par(mfrow = c(1, 3), bty = "l")

S.occ <- tapply(highlow$S, list(highlow$longevity, highlow$treatment), mean)
# S.occ <- S.occ - S.occ[, 4]

plot(seq(20, 200, by = 20), S.occ[, 1], type = "b", lty = 1, ylim = c(0, 1), pch = 19, col = "red", ylab = "S occupancy", xlab = "Longevity")
lines(seq(20, 200, by = 20), S.occ[, 2], type = "b", lty = 2, pch = 19, col = "blue")
lines(seq(20, 200, by = 20), S.occ[, 3], type = "b", lty = 3, pch = 19, col = "black")
lines(seq(20, 200, by = 20), S.occ[, 4], type = "l", lty = 4, pch = 19, col = "grey")

I.occ <- tapply(highlow$I, list(highlow$longevity, highlow$treatment), mean)
# I.occ <- I.occ - I.occ[, 4]

plot(seq(20, 200, by = 20), I.occ[, 1], type = "b", lty = 1, ylim = c(0, 1), pch = 19, col = "red", ylab = "I occupancy", xlab = "Longevity")
lines(seq(20, 200, by = 20), I.occ[, 2], type = "b", lty = 2, pch = 19, col = "blue")
lines(seq(20, 200, by = 20), I.occ[, 3], type = "b", lty = 3, pch = 19, col = "black")
lines(seq(20, 200, by = 20), I.occ[, 4], type = "l", lty = 4, pch = 19, col = "grey")

occ <- tapply(highlow$I + highlow$S, list(highlow$longevity, highlow$treatment), mean)
# occ <- occ - occ[, 4]

plot(seq(20, 200, by = 20), occ[, 1], type = "b", lty = 1, ylim = c(0, 1), pch = 19, col = "red", ylab = "Total occupancy", xlab = "Longevity")
lines(seq(20, 200, by = 20), occ[, 2], type = "b", lty = 2, pch = 19, col = "blue")
lines(seq(20, 200, by = 20), occ[, 3], type = "b", lty = 3, pch = 19, col = "black")
lines(seq(20, 200, by = 20), occ[, 4], type = "l", lty = 4, pch = 19, col = "grey")

dev.off()

# Patch level results
#========================================================

#Filter patch data to include only endemic cases
patch<-out[which(out$Ifin>0 & out$Sfin > 0), ]

#Filter patch data to include only high variance runs
patch<-patch[which(abs(patch$variance - 0.2) < 0.01),]

# #Plotting proportion of time occupied by susceptibles and infecteds as a function of quality
# 
# pdf(paste(dirname(getwd()), "/Manuscript", "/qualityraw", conn, ".pdf", sep=""), height=5, width=10)
# 
# par(mfrow=c(1,2),cex=1)
# 
# smoothScatter(patch$quality,patch$S,ylab="Proportion of time occupied by susceptibles",xlab="Patch Quality")
# lines(loess.smooth(patch$quality,patch$S),lwd=2,col="red")
# smoothScatter(patch$quality,patch$I,ylab="Proportion of time occupied by infecteds",xlab="Patch Quality")
# lines(loess.smooth(patch$quality,patch$I),lwd=2,col="red")
# 
# dev.off()
# 
# pdf(paste(dirname(getwd()), "/Manuscript", "/infevents", conn, ".pdf", sep=""), height=5, width=5)
# 
# par(mfrow=c(1,1),cex=1)
# smoothScatter(patch$quality,patch$inf.events.tot,ylab="Number of infection events",xlab="Patch Quality")
# lines(loess.smooth(patch$quality,patch$inf.events.tot),lwd=3,col="red")
# 
# dev.off()


#===============================================================================
# Figures to show how longevity affects role of quality

# Plotting infection events against quality for range of longevities
plot(seq(0.25, 1.75, by = 0.1), c(1:16), ylim = c(0, 10), type = "n", xlab = "Quality", ylab = "Infections")
for(i in c(40, 60, 80, 100)){
  lines(loess.smooth(patch$quality[patch$longevity == i], patch$inf.events.tot[patch$longevity == i]), type = "b", pch = as.character(i))  
}


# Showing simulation-level variability

# Number of infection events
library(scales)

pdf(paste(getwd(), "/Manuscript", "/infevents", conn, ".pdf", sep=""), height=6, width=8)

reps <- unique(patch$repID)

par(mfrow = c(1, 1))
plot(patch$quality, patch$inf.events.early, type = "n", ylab = "Number of infection events", xlab = "Patch quality", bty = "l")
for(i in 1:length(reps)){
  sim <- patch[patch$repID == reps[i], ]
  try(lines(loess.smooth(sim$quality, sim$inf.events.tot), type = "l", col = alpha("gray", 0.3)))
}
lines(loess.smooth(patch$quality, patch$inf.events.tot), lwd = 2, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 40], patch$inf.events.tot[patch$longevity == 40]), lwd = 1, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 60], patch$inf.events.tot[patch$longevity == 60]), lwd = 1, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 80], patch$inf.events.tot[patch$longevity == 80]), lwd = 1, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 100], patch$inf.events.tot[patch$longevity == 100]), lwd = 1, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 120], patch$inf.events.tot[patch$longevity == 120]), lwd = 1, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 140], patch$inf.events.tot[patch$longevity == 140]), lwd = 1, col = "black")

dev.off()

par(mfrow = c(2, 2))

# Number of infected extinction events
plot(patch$quality, patch$inf.ex, type = "n", ylab = "Number of infected extinctions", xlab = "Patch quality")
for(i in 1:length(reps)){
  sim <- patch[patch$repID == reps[i], ]
  lines(loess.smooth(sim$quality, sim$inf.ex), type = "l", col = alpha("gray", 0.3))
}
lines(loess.smooth(patch$quality, patch$inf.ex), lwd = 2, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 40], patch$inf.ex[patch$longevity == 40]), lwd = 1.5, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 100], patch$inf.ex[patch$longevity == 100]), lwd = 1.5, col = "black")

# Number of susceptible extinction events
plot(patch$quality, patch$susc.ex, type = "n", ylab = "Number of susceptible extinctions", xlab = "Patch quality")
for(i in 1:length(reps)){
  sim <- patch[patch$repID == reps[i], ]
  lines(loess.smooth(sim$quality, sim$susc.ex), type = "l", col = alpha("gray", 0.3))
}
lines(loess.smooth(patch$quality, patch$susc.ex), lwd = 2, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 40], patch$susc.ex[patch$longevity == 40]), lwd = 1.5, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 100], patch$susc.ex[patch$longevity == 100]), lwd = 1.5, col = "black")

# Infected colonizations
plot(patch$quality, patch$inf.col, type = "n", ylab = "Number of infected colonizations", xlab = "Patch quality")
for(i in 1:length(reps)){
  sim <- patch[patch$repID == reps[i], ]
  lines(loess.smooth(sim$quality, sim$inf.col), type = "l", col = alpha("gray", 0.3))
}
lines(loess.smooth(patch$quality, patch$inf.col), lwd = 2, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 40], patch$inf.col[patch$longevity == 40]), lwd = 1.5, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 100], patch$inf.col[patch$longevity == 100]), lwd = 1.5, col = "black")

# Susceptible colonizations
plot(patch$quality, patch$inf.col, type = "n", ylab = "Number of susceptible colonizations", xlab = "Patch quality")
for(i in 1:length(reps)){
  sim <- patch[patch$repID == reps[i], ]
  lines(loess.smooth(sim$quality, sim$susc.col), type = "l", col = alpha("gray", 0.3))
}
lines(loess.smooth(patch$quality, patch$susc.col), lwd = 2, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 40], patch$susc.col[patch$longevity == 40]), lwd = 1.5, col = "black")
lines(loess.smooth(patch$quality[patch$longevity == 100], patch$susc.col[patch$longevity == 100]), lwd = 1.5, col = "black")
